# Generated by Django 5.1.7 on 2026-03-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_name', models.CharField(max_length=64, verbose_name='Steam-имя')),
                ('discord_tag', models.CharField(max_length=64, verbose_name='Discord')),
                ('hours', models.PositiveIntegerField(verbose_name='Часов в Rust')),
                ('region', models.CharField(choices=[('EU', 'EU'), ('RU', 'RU'), ('NA', 'NA'), ('ASIA', 'ASIA')], max_length=8, verbose_name='Регион')),
                ('role', models.CharField(choices=[('raider', 'Raider'), ('builder', 'Builder / Electrician'), ('pvp', 'PVP / Coller'), ('farmer', 'Farmer / Support'), ('any', 'Any')], max_length=16, verbose_name='Роль')),
                ('reason', models.TextField(verbose_name='Почему хочешь к нам')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
