# Generated by Django 5.1.7 on 2026-03-04 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_name', models.CharField(max_length=64, verbose_name='Steam-имя')),
                ('discord_tag', models.CharField(max_length=64, verbose_name='Discord')),
                ('hours', models.PositiveIntegerField(verbose_name='Часов в Rust')),
                ('region', models.CharField(choices=[('EU', 'EU'), ('RU', 'RU'), ('NA', 'NA'), ('ASIA', 'ASIA')], max_length=8, verbose_name='Регион')),
                ('role', models.CharField(choices=[('raider', 'Raider'), ('builder', 'Builder / Electrician'), ('pvp', 'PVP / Coller'), ('farmer', 'Farmer / Support'), ('any', 'Any')], max_length=16, verbose_name='Роль')),
                ('reason', models.TextField(verbose_name='Почему хочешь к нам')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=64, verbose_name='Никнейм (отображаемый)')),
                ('rank', models.CharField(choices=[('leader', 'Leader'), ('co-leader', 'Co-Leader'), ('veteran', 'Veteran'), ('member', 'Member'), ('recruit', 'Recruit')], default='member', max_length=16, verbose_name='Звание')),
                ('specialization', models.CharField(choices=[('raider', 'Raider'), ('builder', 'Builder / Electrician'), ('pvp', 'PVP / Coller'), ('farmer', 'Farmer / Support'), ('any', 'Any')], default='any', max_length=16, verbose_name='Специализация')),
                ('region', models.CharField(choices=[('EU', 'EU'), ('RU', 'RU'), ('NA', 'NA'), ('ASIA', 'ASIA')], default='EU', max_length=8, verbose_name='Регион')),
                ('hours', models.PositiveIntegerField(default=0, verbose_name='Часов в Rust')),
                ('avatar_url', models.URLField(blank=True, default='', verbose_name='Ссылка на аватар')),
                ('discord_tag', models.CharField(blank=True, default='', max_length=64, verbose_name='Discord')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='Дата вступления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='Игрок (аккаунт)')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Состав клана',
                'ordering': ['order', 'nickname'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_name', models.CharField(blank=True, default='', max_length=64, verbose_name='Steam-ник')),
                ('steam_url', models.CharField(blank=True, default='', max_length=256, verbose_name='Steam профиль')),
                ('role', models.CharField(choices=[('raider', 'Raider'), ('builder', 'Builder / Electrician'), ('pvp', 'PVP / Coller'), ('farmer', 'Farmer / Support'), ('any', 'Any')], default='any', max_length=16, verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили игроков',
            },
        ),
        migrations.CreateModel(
            name='WipePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('server_name', models.CharField(max_length=128, verbose_name='Название сервера')),
                ('connect', models.CharField(help_text='Пример: client.connect 185.0.0.1:28015', max_length=128, verbose_name='Коннект (команда)')),
                ('wipe_date', models.DateTimeField(verbose_name='Дата вайпа')),
                ('raid_plan', models.CharField(blank=True, default='', help_text='Пример: Первый рейд — 20:00 МСК / Ночной — 02:00', max_length=256, verbose_name='Расписание рейдов')),
                ('description', models.TextField(blank=True, default='', verbose_name='Доп. информация')),
                ('is_active', models.BooleanField(default=False, help_text='Только один вайп может быть активным', verbose_name='Текущий вайп (закреплён)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('squad', models.ManyToManyField(blank=True, related_name='wipe_posts', to='clan.member', verbose_name='Состав')),
            ],
            options={
                'verbose_name': 'Вайп',
                'verbose_name_plural': 'Вайпы',
                'ordering': ['-created_at'],
            },
        ),
    ]
