# Generated by Django 5.1.7 on 2026-03-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Часов в Rust'),
        ),
    ]
