# Generated by Django 5.1.7 on 2026-03-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0002_userprofile_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='wipepost',
            name='discord_message_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
