# Generated by Django 5.1.7 on 2026-03-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0003_wipepost_discord_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('message_id', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'verbose_name': 'Discord сообщение',
                'verbose_name_plural': 'Discord сообщения',
            },
        ),
    ]
