# Generated by Django 5.1.7 on 2026-03-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0006_userprofile_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='role',
            field=models.CharField(choices=[('leader', 'Лидер'), ('deputy', 'Зам'), ('coller', 'Колер'), ('builder', 'Билдер'), ('electric', 'Электрик'), ('farmer', 'Фармер'), ('combater', 'Комбатер'), ('raider', 'Рейдер'), ('ferm', 'Фермер')], max_length=16, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='member',
            name='specialization',
            field=models.CharField(choices=[('leader', 'Лидер'), ('deputy', 'Зам'), ('coller', 'Колер'), ('builder', 'Билдер'), ('electric', 'Электрик'), ('farmer', 'Фармер'), ('combater', 'Комбатер'), ('raider', 'Рейдер'), ('ferm', 'Фермер')], default='any', max_length=16, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('leader', 'Лидер'), ('deputy', 'Зам'), ('coller', 'Колер'), ('builder', 'Билдер'), ('electric', 'Электрик'), ('farmer', 'Фармер'), ('combater', 'Комбатер'), ('raider', 'Рейдер'), ('ferm', 'Фермер')], default='any', max_length=16, verbose_name='Роль'),
        ),
    ]
