# Generated by Django 5.1.7 on 2026-03-12 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0007_update_role_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, verbose_name='Дата вступления'),
        ),
    ]
