# Generated by Django 5.1.7 on 2026-03-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0008_join_date_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('type', models.CharField(choices=[('vanilla', 'Vanilla'), ('modded', 'Modded'), ('training', 'Training')], default='vanilla', max_length=16, verbose_name='Тип')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=16, verbose_name='Статус')),
                ('players', models.PositiveIntegerField(default=0, verbose_name='Игроков онлайн')),
                ('max_players', models.PositiveIntegerField(default=200, verbose_name='Макс. игроков')),
                ('ping', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пинг (мс)')),
                ('wipe_day', models.CharField(blank=True, default='', max_length=64, verbose_name='День вайпа')),
                ('region', models.CharField(blank=True, default='', max_length=32, verbose_name='Регион')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('category', models.CharField(choices=[('raid', 'Рейд'), ('pvp', 'PVP'), ('build', 'Строительство'), ('guide', 'Гайд')], default='raid', max_length=16, verbose_name='Категория')),
                ('duration', models.CharField(blank=True, default='', max_length=16, verbose_name='Длительность')),
                ('views', models.CharField(blank=True, default='', max_length=16, verbose_name='Просмотры')),
                ('date', models.CharField(blank=True, default='', max_length=32, verbose_name='Дата')),
                ('url', models.URLField(blank=True, default='', verbose_name='Ссылка на видео')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['order', '-id'],
            },
        ),
    ]
