# Generated by Django 5.1.7 on 2026-03-28 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0012_bot_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='name',
            field=models.CharField(default='Main', max_length=64, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='cityzone',
            name='server',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_zone', to='clan.botconfig', verbose_name='Сервер'),
        ),
    ]
